apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: morohub-poc

resources:
- 00-namespace.yaml
- 10-config.yaml
- 20-postgres.yaml
- 30-migrate-job.yaml
- 40-web.yaml
- 50-ingress.yaml
- 60-hpa.yaml
- 70-pdb.yaml
- 80-networkpolicy.yaml

commonLabels:
  app.kubernetes.io/part-of: morohub-poc

# Override image tag in one place, e.g. with:
#   kustomize edit set image ghcr.io/REPLACE_ME/kubernetes-poc-nextjs:v0.1.0
images:
- name: ghcr.io/REPLACE_ME/kubernetes-poc-nextjs
  newName: ghcr.io/kakamana/kubernetes-poc-nextjs
  newTag: v0.1.0
